class Word {
	constructor (pinyin, character, translation){
    	this.pinyin = pinyin;
        this.character = character;
        this.translation = translation;
    }
}
wordArr = [
	new Word('wǒ', '我', 'I, me'),
new Word('wǒmen', '我们', 'we, us （pl.）'),
new Word('nǐ', '你', 'you'),
new Word('nǐmen', '你们', 'you (pl.)'),
new Word('tā', '他', 'he, him'),
new Word('tā', '她', 'she, her'),
new Word('tāmen', '他们', 'they (male+female / male，pl.)'),
new Word('tāmen', '她们', 'they (females, pl.)'),
new Word('zhè ( zhèr)', '这 (这儿)', 'here, this'),
new Word('nà (nàr)', '那 (那儿)', 'there, that'),
new Word('nǎ (nǎr)', '哪（哪儿）', 'where'),
new Word('shéi', '谁', 'who'),
new Word('shénme', '什么', 'what, why'),
new Word('duōshǎo', '多少', 'how many, how much'),
new Word('jǐ', '几', 'a few, how many'),
new Word('zěnme', '怎么', 'how'),
new Word('zěnmeyàng', '怎么样', 'how about'),
new Word('nín', '您', 'you'),
new Word('tā', '它', 'it'),
new Word('dàjiā', '大家', 'everyone'),
new Word('měi', '每', 'every'),
new Word('wèishénme', '为什么', 'why'),
new Word('yī', '一', 'one'),
new Word('èr', '二', 'two'),
new Word('sān', '三', 'three'),
new Word('sì', '四', 'four'),
new Word('wǔ', '五', 'five'),
new Word('liù', '六', 'six'),
new Word('qī', '七', 'seven'),
new Word('bā', '八', 'eight'),
new Word('jiǔ', '九', 'nine'),
new Word('shí', '十', 'ten'),
new Word('líng', '零', 'zero'),
new Word('liǎng', '两', 'two'),
new Word('bǎi', '百', 'hundred'),
new Word('qiān', '千', 'thousand'),
new Word('dìyī', '第一', 'first'),
new Word('gè', '个', 'one, a, an'),
new Word('suì', '岁', 'year'),
new Word('běn', '本', 'volume'),
new Word('xiē', '些', 'some'),
new Word('kuài', '块', 'piece'),
new Word('cì', '次', 'number'),
new Word('gōngjīn', '公斤', 'kilogram'),
new Word('yuán', '元', 'yuan'),
new Word('jiàn', '件', 'piece'),
new Word('zhāng', '张', 'sheet'),
new Word('bù', '不', 'no'),
new Word('méi', '没', 'no'),
new Word('hěn', '很', 'quite, very'),
new Word('tài', '太', 'too'),
new Word('dōu', '都', 'all'),
new Word('bié', '别', 'other'),
new Word('fēicháng', '非常', 'very'),
new Word('yě', '也', 'likewise'),
new Word('hái', '还', 'repay'),
new Word('zuì', '最', 'most'),
new Word('zhēn', '真', 'real'),
new Word('zhèngzài', '正在', 'be being'),
new Word('yǐjīng', '已经', 'already'),
new Word('yìqǐ', '一起', 'together'),
new Word('zài', '再', 'again'),
new Word('jiǜ', '就', 'at once'),
new Word('hé', '和', 'and'),
new Word('yīnwèi', '因为', 'because'),
new Word('suǒyǐ', '所以', 'so'),
new Word('dànshì', '但是', 'but'),
new Word('zài', '在', 'in, at'),
new Word('cóng', '从', 'from'),
new Word('duì', '对', 'right'),
new Word('cǐ', '此', 'this'),
new Word('xiàng', '向', 'towards'),
new Word('lí', '离', 'leave'),
new Word('de', '的', 'possession'),
new Word('le', '了', 'action is done'),
new Word('ma', '吗', 'question element'),
new Word('ne', '呢', 'to build a question based on already mentioned subjects'),
new Word('de', '得', 'appreciation'),
new Word('zhe', '着', 'in progress'),
new Word('guo', '过', 'past'),
new Word('ba', '吧', "Let's"),
new Word('wèi', '喂', 'hello'),
new Word('jiā', '家', 'home'),
new Word('xuéxiào', '学校', 'school'),
new Word('fàn guǎn', '饭馆', 'restaurant'),
new Word('shāngdiàn', '商店', 'store'),
new Word('yīyuàn', '医院', 'hospital'),
new Word('huǒchēzhàn', '火车站', 'train station'),
new Word('zhōngguó', '中国', 'China'),
new Word('jīchǎng', '机场', 'airport'),
new Word('jiàoshì', '教室', 'classroom'),
new Word('fángjiān', '房间', 'room'),
new Word('lù', '路', 'road'),
new Word('běijīng', '北京', 'Beijing'),
new Word('shàng', '上', 'up'),
new Word('xià', '下', 'below'),
new Word('qiánmiàn', '前面', 'front'),
new Word('hòumiàn', '后面', 'behind'),
new Word('zuǒbiān', '左边', 'left'),
new Word('yòubiān', '右边', 'right'),
new Word('wài', '外', 'out'),
new Word('pángbiān', '旁边', 'side'),
new Word('lǐmiàn', '里面', 'inside'),
new Word('jīntiān', '今天', 'today'),
new Word('míngtiān', '明天', 'tomorrow'),
new Word('zuótiān', '昨天', 'yesterday'),
new Word('shàngwǔ', '上午', 'morning'),
new Word('zhōngwǔ', '中午', 'noon'),
new Word('xiàwǔ', '下午', 'afternoon'),
new Word('nián', '年', 'year'),
new Word('yuè', '月', 'month'),
new Word('rì', '日', 'day'),
new Word('xīngqī', '星期', 'week'),
new Word('diǎn', '点', 'dot, spot'),
new Word('fēnzhōng', '分钟', 'minute'),
new Word('xiànzài', '现在', 'now'),
new Word('shíhóu', '时候', 'time'),
new Word('zǎoshàng', '早上', 'morning'),
new Word('wǎnshàng', '晚上', 'night'),
new Word('xiǎoshí', '小时', 'hour'),
new Word('shíjiān', '时间', 'time'),
new Word('qùnián', '去年', 'last year'),
new Word('hào', '号', 'number'),
new Word('shēngrì', '生日', 'birthday'),
new Word('bàba', '爸爸', 'father'),
new Word('māma', '妈妈', 'mother'),
new Word('érzi', '儿子', 'son'),
new Word('nǚér', '女儿', 'daughter'),
new Word('lǎoshī', '老师', 'teacher'),
new Word('xuéshēng', '学生', 'student'),
new Word('tóngxué', '同学', 'shoolmate'),
new Word('péngyǒu', '朋友', 'friend'),
new Word('yīshēng', '医生', 'doctor'),
new Word('xiānshēng', '先生', 'sir'),
new Word('xiǎojiě', '小姐', 'Miss'),
new Word('gēge', '哥哥', 'brother'),
new Word('jiějie', '姐姐', 'sister'),
new Word('dìdi', '弟弟', 'younger brother'),
new Word('mèimei', '妹妹', 'sis'),
new Word('zhàngfu', '丈夫', 'husband'),
new Word('qīzi', '妻子', 'wife'),
new Word('háizi', '孩子', 'child'),
new Word('nánrén', '男人', 'man'),
new Word('nǚrén', '女人', 'woman'),
new Word('fúwùyuán', '服务员', 'waiter'),
new Word('yīfu', '衣服', 'cloth'),
new Word('shuǐ', '水', 'water'),
new Word('cài', '菜', 'vegetable'),
new Word('mǐfàn', '米饭', 'rice'),
new Word('shuǐguǒ', '水果', 'fruit'),
new Word('píngguǒ', '苹果', 'apple'),
new Word('chá', '茶', 'tea'),
new Word('bēizi', '杯子', 'cup'),
new Word('qián', '钱', 'money'),
new Word('fēijī', '飞机', 'airplane'),
new Word('chūzūchē', '出租车', 'taxi'),
new Word('diànshì', '电视', 'television'),
new Word('diànnǎo', '电脑', 'computer'),
new Word('diànyǐng', '电影', 'movie'),
new Word('tiānqì', '天气', 'weather'),
new Word('māo', '猫', 'cat'),
new Word('gǒu', '狗', 'dog'),
new Word('dōngxī', '东西', 'thing'),
new Word('yú', '鱼', 'fish'),
new Word('yángròu', '羊肉', 'mutton'),
new Word('niúnǎi', '牛奶', 'milk'),
new Word('jīdàn', '鸡蛋', 'egg'),
new Word('xīguā', '西瓜', 'watermelon'),
new Word('kāfēi', '咖啡', 'coffee'),
new Word('zìxíngchē', '自行车', 'bike'),
new Word('chuán', '船', 'boat'),
new Word('xué', '雪', 'snow'),
new Word('yào', '药', 'medicine'),
new Word('shǒujī', '手机', 'phone'),
new Word('shǒubiǎo', '手表', 'watch'),
new Word('yǎnjīng', '眼睛', 'eye'),
new Word('shēntǐ', '身体', 'body'),
new Word('gōnggòngqìchē', '公共汽车', 'bus'),
new Word('bàozhǐ', '报纸', 'newspaper'),
new Word('rén', '人', 'person'),
new Word('míngzi', '名字', 'name'),
new Word('shū', '书', 'book'),
new Word('hànyǔ', '汉语', 'Chinese'),
new Word('zì', '字', 'character'),
new Word('zhuōōzi', '桌子', 'desk'),
new Word('yǐzi', '椅子', 'chair'),
new Word('mén', '门', 'door'),
new Word('tí', '题', 'topic'),
new Word('kè', '课', 'lesson'),
new Word('xìng', '姓', 'surname'),
new Word('wèntí', '问题', 'question'),
new Word('shìqing', '事情', 'matter'),
new Word('kǎoshì', '考试', 'exam'),
new Word('piào', '票', 'ticket'),
new Word('yìsi', '意思', 'meaning'),
new Word('yánsè', '颜色', 'color'),
new Word('xièxiè', '谢谢', 'thank'),
new Word('búkèqì', '不客气', 'you are welcome'),
new Word('zàijiàn', '再见', 'good-bye'),
new Word('qǐng', '请', 'please'),
new Word('duìbùqǐ', '对不起', 'sorry'),
new Word('méiguānxì', '没关系', 'It doesn’t matter'),
new Word('huānyíng', '欢迎', 'welcome'),
new Word('shì', '是', 'am, is, are'),
new Word('yǒu', '有', 'have'),
new Word('kàn', '看', 'look'),
new Word('tīng', '听', 'listen'),
new Word('shuōhuà', '说话', 'speak'),
new Word('dú', '读', 'read'),
new Word('xiě', '写', 'write'),
new Word('kànjiàn', '看见', 'see'),
new Word('jiào', '叫', 'call'),
new Word('lái', '来', 'come'),
new Word('huí', '回', 'return'),
new Word('qù', '去', 'go'),
new Word('chī', '吃', 'eat'),
new Word('hē', '喝', 'drink'),
new Word('shuìjiào', '睡觉', 'sleep'),
new Word('dǎdiànhuà', '打电话', 'call up'),
new Word('zuò', '做', 'do'),
new Word('mǎi', '买', 'buy'),
new Word('kāi', '开', 'open'),
new Word('zuò', '坐', 'sit'),
new Word('zhù', '住', 'live'),
new Word('xuéxí', '学习', 'study'),
new Word('gōngzuò', '工作', 'work'),
new Word('xiàyǔ', '下雨', 'rain'),
new Word('wèn', '问', 'ask'),
new Word('zǒu', '走', 'walk'),
new Word('jìn', '进', 'enter'),
new Word('chū', '出', 'come'),
new Word('pǎobù', '跑步', 'run'),
new Word('dào', '到', 'arrive'),
new Word('chuān', '穿', 'wear'),
new Word('xǐ', '洗', 'wash'),
new Word('gěi', '给', 'give'),
new Word('zhǎo', '找', 'find'),
new Word('dǒng', '懂', 'understand'),
new Word('xiào', '笑', 'smile'),
new Word('huídá', '回答', 'answer'),
new Word('gàosù', '告诉', 'tell'),
new Word('zhǔnbèi', '准备', 'prepare'),
new Word('kāishǐ', '开始', 'begin'),
new Word('jièshào', '介绍', 'introduce'),
new Word('bāngzhù', '帮助', 'help'),
new Word('wán', '玩', 'play'),
new Word('sòng', '送', 'present'),
new Word('děng', '等', 'wait'),
new Word('ràng', '让', 'let'),
new Word('qǐchuáng', '起床', 'get up'),
new Word('chànggē', '唱歌', 'sing'),
new Word('tiàowǔ', '跳舞', 'dance'),
new Word('lǚyóu', '旅游', 'travel'),
new Word('shàngbān', '上班', 'be on duty'),
new Word('shēngbìng', '生病', 'fall ill'),
new Word('xiūxi', '休息', 'rest'),
new Word('yùndòng', '运动', 'exercise'),
new Word('yóuyǒng', '游泳', 'swim'),
new Word('tīzúqiú', '踢足球', 'play footbal'),
new Word('dǎlánqiú', '打篮球', 'play basketball'),
new Word('wán', '完', 'finish'),
new Word('ài', '爱', 'love'),
new Word('xǐhuān', '喜欢', 'love, like'),
new Word('xiǎng', '想', 'want'),
new Word('rènshi', '认识', 'know'),
new Word('juédé', '觉得', 'think'),
new Word('zhīdào', '知道', 'know'),
new Word('xīwàng', '希望', 'hope'),
new Word('huì', '会', 'can'),
new Word('néng', '能', 'can, be able to'),
new Word('kěyǐ', '可以', 'can'),
new Word('yào', '要', 'ask for'),
new Word('kěnéng', '可能', 'may'),
new Word('hǎo', '好', 'good'),
new Word('dà', '大', 'big'),
new Word('xiǎo', '小', 'small'),
new Word('duō', '多', 'many, much'),
new Word('shǎo', '少', 'few, little'),
new Word('lěng', '冷', 'cold'),
new Word('rè', '热', 'hot'),
new Word('gāoxìng', '高兴', 'happy'),
new Word('piàoliàng', '漂亮', 'beautiful'),
new Word('gāo', '高', 'tall'),
new Word('hóng', '红', 'red'),
new Word('bái', '白', 'white'),
new Word('hēi', '黑', 'black'),
new Word('máng', '忙', 'busy'),
new Word('kuài', '快', 'fast'),
new Word('màn', '慢', 'slow'),
new Word('yuǎn', '远', 'far'),
new Word('jìn', '近', 'close'),
new Word('hǎochī', '好吃', 'delicious'),
new Word('lèi', '累', 'tired'),
new Word('cháng', '长', 'long'),
new Word('xīn', '新', 'new'),
new Word('guì', '贵', 'expensive'),
new Word('piányi', '便宜', 'cheap'),
new Word('qíng', '晴', 'fine'),
new Word('yīn', '阴', 'cloudy'),
new Word('cuò', '错', 'wrong'),
new Word('kuàilè', '快乐', 'happy')
]
