class Word {
	constructor (pinyin, character, translation){
    	this.pinyin = pinyin;
        this.character = character;
        this.translation = translation;
    }
}
wordArr = [
	new Word('a', '啊 ', 'auxiliary word'),
  new Word('àiqíng', '爱情', 'Love'),
  new Word('ài rén', '爱人', 'lover'),
  new Word('ānjìng', '安静', 'Be quiet'),
  new Word('ānquán', '安全', 'security'),
  new Word('bái sè', '白色', 'white'),
  new Word('bān zhǎng', '班长', 'monitor; squad leader'),
  new Word('bàn', '办', 'do'),
  new Word('bànfǎ', '办法', 'Way'),
  new Word('bàngōngshì', '办公室', 'Office'),
  new Word('bàn yè', '半夜', 'midnight'),
  new Word('bāngzhù', '帮助', 'Help'),
  new Word('bǎo', '饱', 'full'),
  new Word('bàomíng', '报名', 'sign up'),
  new Word('bàozhǐ', '报纸', 'Newspaper'),
  new Word('běifāng', '北方', 'north'),
  new Word('bēi', '背（动）', 'carry on the back; shoulder'),
  new Word('bǐrú', '比如', 'such as'),
  new Word('bǐ rú shuō', '比如说', 'for example'),
  new Word('bǐ', '笔', 'pen'),
  new Word('bǐ jì', '笔记', 'note; notes'),
  new Word('bǐjìběn', '笔记本', 'Notebook'),
  new Word('bìxū', '必须', 'Must'),
  new Word('biān', '边', 'side'),
  new Word('biàn', '变', 'change'),
  new Word('biàn chéng', '变成', 'become; change into'),
  new Word('biàn', '遍', 'Times'),
  new Word('biǎo', '表', 'watch'),
  new Word('biǎoshì', '表示', 'Express'),
  new Word('bú cuò', '不错', 'not bad; pretty good'),
  new Word('bú dàn', '不但', 'not only'),
  new Word('bú gòu', '不够', 'not enough'),
  new Word('búguò', '不过', 'However'),
  new Word('bú tài', '不太', 'not too; not very much'),
  new Word('bú yào', '不要', 'don’t'),
  new Word('bù hǎo yì sī', '不好意思', 'sorry; feel embarrassed'),
  new Word('bù jiǔ', '不久', 'soon'),
  new Word('bù mǎn', '不满', 'dissatisfied'),
  new Word('bùrú', '不如', 'not as good as'),
  new Word('bù shǎo', '不少', 'not a few; a lot'),
  new Word('bù tóng', '不同', 'different'),
  new Word('bù xíng', '不行', 'no way; be out of the question'),
  new Word('bù yī dìng', '不一定', 'not necessarily; uncertain'),
  new Word('bù yī huìr', '不一会儿', 'in a moment; in a little while; soon'),
  new Word('bùfen', '部分', 'Part'),
  new Word('cái', '才（副）', 'only; just'),
  new Word('càidān', '菜单', 'menu'),
  new Word('cānguān', '参观', 'visit'),
  new Word('cānjiā', '参加', 'participate in'),
  new Word('cǎo', '草', 'grass'),
  new Word('cǎo dì', '草地', 'grass; lawn'),
  new Word('céng', '层', 'layer'),
  new Word('chá', '查', 'search; check'),
  new Word('chàbuduō', '差不多', 'Almost'),
  new Word('cháng', '长', 'long'),
  new Word('cháng jiàn', '常见', 'common'),
  new Word('cháng yòng', '常用', 'in common use'),
  new Word('chǎng', '场', 'site'),
  new Word('chāoguò', '超过', 'Exceed'),
  new Word('chāoshì', '超市', 'Supermarket'),
  new Word('chē liàng', '车辆', 'car; vehicle'),
  new Word('chēng', '称¹（动）', 'call; say'),
  new Word('chéng', '成（动）', 'become; finish'),
  new Word('chéngjì', '成绩', 'achievement'),
  new Word('chéngwéi', '成为', 'Become'),
  new Word('chóngfù', '重复', 'repeat'),
  new Word('chóngxīn', '重新', 'again'),
  new Word('chūfā', '出发', 'Set out'),
  new Word('chū guó', '出国', 'go abroad'),
  new Word('chū kǒu', '出口（名）', 'export'),
  new Word('chū mén', '出门', 'go out'),
  new Word('chūshēng', '出生', 'Birth'),
  new Word('chūxiàn', '出现', 'Appear'),
  new Word('chū yuàn', '出院', 'discharged; leave hospital'),
  new Word('chū zū', '出租', 'rent'),
  new Word('chūzūchē', '出租车', 'Taxi'),
  new Word('chuán', '船', 'ship'),
  new Word('chuī', '吹', 'blow'),
  new Word('chūn jié', '春节', 'Spring Festival; Chinese New Year'),
  new Word('chūn tiān', '春天', 'spring'),
  new Word('cí', '词', 'word'),
  new Word('cídiǎn', '词典', 'Dictionary'),
  new Word('cíyǔ', '词语', 'terms'),
  new Word('cóng xiǎo', '从小', 'from childhood'),
  new Word('dāying', '答应', 'promise'),
  new Word('dǎgōng', '打工', 'Work'),
  new Word('dǎsuàn', '打算', 'Plan'),
  new Word('dǎyìn', '打印', 'Print'),
  new Word('dà bù fèn', '大部分', 'most'),
  new Word('dà dà', '大大', 'greatly; enormously'),
  new Word('dà duō shù', '大多数', 'most; great majority'),
  new Word('dà hǎi', '大海', 'sea'),
  new Word('dàjiā', '大家', 'everybody'),
  new Word('dà liàng', '大量', 'a lot of; lots of'),
  new Word('dà mén', '大门', 'door; gate'),
  new Word('dà rén', '大人', 'adult'),
  new Word('dà shēng', '大声', 'loud'),
  new Word('dà xiǎo', '大小', 'size'),
  new Word('dà yī', '大衣', 'overcoat'),
  new Word('dà zì rán', '大自然', 'nature'),
  new Word('dài', '带', 'belt'),
  new Word('dài lái', '带来', 'bring'),
  new Word('dānwèi', '单位', 'Company'),
  new Word('dàn', '但', 'but; however'),
  new Word('dàn shì', '但是', 'but; however'),
  new Word('dàn', '蛋', 'egg'),
  new Word('dāng', '当', 'When'),
  new Word('dāngshí', '当时', 'at that time'),
  new Word('dǎo', '倒', 'fall, topple, fail'),
  new Word('dàochù', '到处', 'everywhere'),
  new Word('dào', '倒', 'inverted'),
  new Word('dào', '道', 'road; way; path'),
  new Word('dàolǐ', '道理', 'truth'),
  new Word('dào lù', '道路', 'road; way; path'),
  new Word('dé', '得', 'get'),
  new Word('dé chū', '得出', 'obtain results; reach conclusion'),
  new Word('de huà', '的话', 'if'),
  new Word('de', '得', 'auxiliary verb'),
  new Word('dēng', '灯', 'lamp'),
  new Word('děng', '等（助、名）', 'etc.; and so on'),
  new Word('děng dào', '等到', 'wait until; by the time'),
  new Word('děngyú', '等于', 'Be equal to'),
  new Word('dī', '低', 'low'),
  new Word('dìqiú', '地球', 'earth'),
  new Word('dìtiě', '地铁', 'metro'),
  new Word('dì tiě zhàn', '地铁站', 'subway station'),
  new Word('diǎn tóu', '点头', 'nod'),
  new Word('diàn', '店', 'shop; store'),
  new Word('diào', '掉', 'fall'),
  new Word('dōng běi', '东北', 'northeast'),
  new Word('dōng fāng', '东方', 'east'),
  new Word('dōng nán', '东南', 'southeast'),
  new Word('dōng tiān', '冬天', 'winter'),
  new Word('dǒng', '懂', 'understand'),
  new Word('dǒng de', '懂得', 'know; understand; comprehend'),
  new Word('dòngwù', '动物', 'Animal'),
  new Word('dòng wù yuán', '动物园', 'zoo'),
  new Word('dú yīn', '读音', 'pronunciation'),
  new Word('dù', '度', 'degree; limit'),
  new Word('duǎn', '短', 'short'),
  new Word('duǎnxìn', '短信', 'message'),
  new Word('duàn', '段', 'paragraph'),
  new Word('duì', '队', 'team'),
  new Word('duì zhǎng', '队长', 'team leader; captain'),
  new Word('duì', '对（介、动）', 'to; at; face; be opposite; answer'),
  new Word('duìhuà', '对话', 'dialogue'),
  new Word('duìmiàn', '对面', 'Opposite side'),
  new Word('duō', '多（副）', 'much more; far more'),
  new Word('duō jiǔ', '多久', 'how long'),
  new Word('duōme', '多么', 'what'),
  new Word('duō shù', '多数', 'most; majority'),
  new Word('duō yún', '多云', 'cloudy'),
  new Word('ér qiě', '而且', 'and'),
  new Word('fā', '发', 'send out'),
  new Word('fāxiàn', '发现', 'find'),
  new Word('fàn guǎn', '饭馆', 'restaurant'),
  new Word('fāngbiàn', '方便', 'convenient'),
  new Word('fāng biàn miàn', '方便面', 'Instant noodles'),
  new Word('fāngfǎ', '方法', 'Method'),
  new Word('fāngmiàn', '方面', 'Aspect'),
  new Word('fāngxiàng', '方向', 'direction'),
  new Word('fàng xià', '放下', 'put down; lay down; drop'),
  new Word('fàngxīn', '放心', 'Don’t worry'),
  new Word('fēn', '分（动）', 'divide; part; distribute'),
  new Word('fēn kāi', '分开', 'separate; part'),
  new Word('fēn shù', '分数', 'score; mark; fraction'),
  new Word('fēnzhōng', '分钟', 'Minute'),
  new Word('fèn', '份', 'share'),
  new Word('fēng', '封（量）', '(measure word)'),
  new Word('fú wù', '服务', 'service'),
  new Word('fùxí', '复习', 'Review'),
  new Word('gāi', '该（动）', 'deserve; should; owe'),
  new Word('gǎi', '改', 'change; correct; revise; switch over'),
  new Word('gǎibiàn', '改变', 'change'),
  new Word('gānbēi', '干杯', 'Cheers!'),
  new Word('gǎn dào', '感到', 'feel; sense'),
  new Word('gǎndòng', '感动', 'Be moved'),
  new Word('gǎnjué', '感觉', 'feel'),
  new Word('gǎnxiè', '感谢', 'Thank'),
  new Word('gànhuór', '干活儿', 'work on a job'),
  new Word('gāng', '刚', 'just'),
  new Word('gāngcái', '刚才', 'just'),
  new Word('gāng gāng', '刚刚', 'just; only; just a moment ago'),
  new Word('gāojí', '高级', 'senior'),
  new Word('gāo zhōng', '高中', 'senior high school'),
  new Word('gèzi', '个子', 'Height'),
  new Word('gèng', '更', 'more'),
  new Word('gōnggòngqìchē', '公共汽车', 'Bus'),
  new Word('gōng jiāo chē', '公交车', 'bus'),
  new Word('gōngjīn', '公斤', 'Kg.'),
  new Word('gōnglǐ', '公里', 'kilometre'),
  new Word('gōng lù', '公路', 'highway; highroad'),
  new Word('gōngpíng', '公平', 'fair'),
  new Word('gōngsī', '公司', 'company'),
  new Word('gōngyuán', '公园', 'Park'),
  new Word('gǒu', '狗', 'Dog'),
  new Word('gòu', '够', 'enough'),
  new Word('gùshi', '故事', 'Story'),
  new Word('gùyì', '故意', 'deliberately'),
  new Word('gùkè', '顾客', 'customer'),
  new Word('guān jī', '关机', 'shutdown'),
  new Word('guānxīn', '关心', 'Care for'),
  new Word('guāndiǎn', '观点', 'viewpoint'),
  new Word('guǎngchǎng', '广场', 'square'),
  new Word('guǎnggào', '广告', 'Advertisement'),
  new Word('guójì', '国际', 'international'),
  new Word('guò lái', '过来', 'come; come over'),
  new Word('guò nián', '过年', 'celebrate the New Year'),
  new Word('guò qù', '过去（动）', 'go over; pass by'),
  new Word('guò', '过', 'cross; pass; spend; live'),
  new Word('hǎi', '海', 'sea'),
  new Word('hǎi biān', '海边', 'seaside'),
  new Word('hǎn', '喊', 'shout'),
  new Word('hǎo', '好（副）', 'well; fine; okay'),
  new Word('hǎochu', '好处', 'benefit'),
  new Word('hǎo duō', '好多', 'many; a lot of'),
  new Word('hǎo jiǔ', '好久', 'for a long time; long'),
  new Word('hǎo rén', '好人', 'good person'),
  new Word('hǎo shì', '好事', 'good deed; good thing'),
  new Word('hǎoxiàng', '好像', 'Be like'),
  new Word('héshì', '合适', 'appropriate'),
  new Word('hé', '河', 'river'),
  new Word('hēi', '黑', 'black'),
  new Word('hēibǎn', '黑板', 'blackboard'),
  new Word('hēi sè', '黑色', 'black'),
  new Word('hóng', '红', 'red'),
  new Word('hóng sè', '红色', 'red'),
  new Word('hòulái', '后来', 'later'),
  new Word('hūrán', '忽然', 'suddenly'),
  new Word('hú', '湖', 'lake'),
  new Word('hùzhào', '护照', 'passport'),
  new Word('huā', '花（动）', 'spend; expend'),
  new Word('huā yuán', '花园', 'garden'),
  new Word('huà', '画', 'painting'),
  new Word('huà jiā', '画家', 'painter; artist'),
  new Word('huàr', '画儿', 'painting; drawing'),
  new Word('huài chù', '坏处', 'disadvantage; harm'),
  new Word('huài rén', '坏人', 'bad person'),
  new Word('huānyíng', '欢迎', 'Welcome'),
  new Word('huàn', '换', 'change'),
  new Word('huáng', '黄', 'yellow'),
  new Word('huáng sè', '黄色', 'yellow'),
  new Word('huí', '回（量）', '(measure word)'),
  new Word('huí guó', '回国', 'return home from abroad'),
  new Word('huì', '会（名）', 'meeting; gathering; conference; union; party'),
  new Word('huódòng', '活动', 'activity'),
  new Word('huò', '或', 'or'),
  new Word('huòzhě', '或者', 'perhaps'),
  new Word('jīhuì', '机会', 'Opportunity'),
  new Word('jī', '鸡', 'chicken'),
  new Word('jí', '级', 'level; rank; grade; degree; step'),
  new Word('jí', '急', 'fast; anxious; urgent; annoyed'),
  new Word('jìhuà', '计划', 'plan'),
  new Word('jì suàn jī', '计算机', 'computer'),
  new Word('jiā', '加', 'add; increase; put in'),
  new Word('jiā yóu', '加油', 'oil; refuel; make an all-out effort'),
  new Word('jiā', '家（科学家）', 'noun suffix (scientist)'),
  new Word('jiātíng', '家庭', 'Family'),
  new Word('jiā zhǎng', '家长', 'parent; the head of the family'),
  new Word('jiǎ', '假', 'false '),
  new Word('jià qī', '假期', 'holiday; vacation'),
  new Word('jiǎnchá', '检查', 'inspect; check'),
  new Word('jiàn dào', '见到', 'see'),
  new Word('jiàn guò', '见过', 'seen; have seen'),
  new Word('jiàn', '件', 'piece'),
  new Word('jiànkāng', '健康', 'Healthy'),
  new Word('jiǎng', '讲', 'speak'),
  new Word('jiǎng huà', '讲话', 'speak; talk'),
  new Word('jiāo', '交', 'hand over'),
  new Word('jiāo gěi', '交给', 'hand over'),
  new Word('jiāo péng yǒu', '交朋友', 'make friends'),
  new Word('jiāotōng', '交通', 'traffic'),
  new Word('jiǎo', '角', 'horn'),
  new Word('jiǎodù', '角度', 'angle'),
  new Word('jiǎozi', '饺子', 'Dumplings'),
  new Word('jiǎo', '脚', 'foot'),
  new Word('jiào zuò', '叫作', 'be called; be known as'),
  new Word('jiào shī', '教师', 'teacher'),
  new Word('jiàoshì', '教室', 'Classroom'),
  new Word('jiào xué', '教学', 'teach'),
  new Word('jiàoyù', '教育', 'education'),
  new Word('jiē', '接', 'meet， pick'),
  new Word('jiē dào', '接到', 'receive'),
  new Word('jiēshòu', '接受', 'accept'),
  new Word('jiē xià lái', '接下来', 'next'),
  new Word('jiēzhe', '接着', 'Next'),
  new Word('jiē', '街', 'street'),
  new Word('jié', '节（名、量）', 'festival; holiday; joint; (measure word)'),
  new Word('jiémù', '节目', 'program'),
  new Word('jiérì', '节日', 'festival'),
  new Word('jiéguǒ', '结果', 'Result'),
  new Word('jiè', '借', 'borrow'),
  new Word('jīn', '斤', 'a unit of weight (=1/2 kilogram)'),
  new Word('jīn hòu', '今后', 'from now on; in the future'),
  new Word('jìn rù', '进入', 'enter; go in; join'),
  new Word('jìnxíng', '进行', 'Conduct'),
  new Word('jìn', '近', 'near'),
  new Word('jīngcháng', '经常', 'Often'),
  new Word('jīngguò', '经过', 'after, through'),
  new Word('jīnglǐ', '经理', 'manager'),
  new Word('jiǔ', '酒', 'alcohol; liqueur'),
  new Word('jiǔ diàn', '酒店', 'hotel'),
  new Word('jiù yào', '就要', 'be going to; be about to'),
  new Word('jǔ', '举', 'lift'),
  new Word('jǔ shǒu', '举手', 'raise one’s hand or hands'),
  new Word('jǔxíng', '举行', 'hold'),
  new Word('jù', '句', 'sentence'),
  new Word('jùzi', '句子', 'sentence'),
  new Word('kǎ', '卡', 'card'),
  new Word('kāi jī', '开机', 'starting up'),
  new Word('kāixīn', '开心', 'Happy'),
  new Word('kāi xué', '开学', 'school opens; term begins'),
  new Word('kànfǎ', '看法', 'view'),
  new Word('kǎo shēng', '考生', 'examinee'),
  new Word('kào', '靠', 'lean'),
  new Word('kē', '科', 'subject; family; section'),
  new Word('kēxué', '科学', 'science'),
  new Word('kě’ài', '可爱', 'Lovely'),
  new Word('kěnéng', '可能', 'Probably'),
  new Word('kěpà', '可怕', 'dreadful'),
  new Word('kěshì', '可是', 'however'),
  new Word('kěyǐ', '可以', 'Sure'),
  new Word('kè', '克', 'gram'),
  new Word('kè', '刻（量）', 'a quarter (of an hour)'),
  new Word('kèrén', '客人', 'Guest'),
  new Word('kè táng', '课堂', 'classroom'),
  new Word('kōngqì', '空气', 'atmosphere'),
  new Word('kū', '哭', 'cry'),
  new Word('kuài cān', '快餐', 'fast food'),
  new Word('kuài diǎnr', '快点儿', 'hurry up'),
  new Word('kuàilè', '快乐', 'happy'),
  new Word('kuài yào', '快要', 'be about to; be going to'),
  new Word('kuàizi', '筷子', 'chopsticks'),
  new Word('lā', '拉', 'pull'),
  new Word('láizì', '来自', 'Come from'),
  new Word('lán', '蓝', 'blue'),
  new Word('lán sè', '蓝色', 'blue'),
  new Word('lán qiú', '篮球', 'basketball'),
  new Word('lǎo', '老（副）', 'always; constantly'),
  new Word('lǎo （ lǎo wáng ）', '老（老王）', 'noun prefix (Lao Wang)'),
  new Word('lǎo nián', '老年', 'elderly'),
  new Word('lǎo péng yǒu', '老朋友', 'old friend'),
  new Word('lǎo shì', '老是', 'always; all times'),
  new Word('lí', '离', 'leave'),
  new Word('líkāi', '离开', 'leave'),
  new Word('lǐwù', '礼物', 'gift'),
  new Word('lǐ tou', '里头', 'inside'),
  new Word('lǐxiǎng', '理想', 'ideal'),
  new Word('lìrú', '例如', 'for example'),
  new Word('lì zi', '例子', 'example'),
  new Word('liǎn', '脸', 'face'),
  new Word('liàn', '练', 'practice; train'),
  new Word('liànxí', '练习', 'Practice'),
  new Word('liáng', '凉', 'cool'),
  new Word('liángkuai', '凉快', 'Pleasantly cool'),
  new Word('liǎng', '两（量）', 'a unit of weight (=50 grams)'),
  new Word('liàng', '亮', 'bright'),
  new Word('liàng', '辆', 'Car (measure word)'),
  new Word('líng xià', '零下', 'below zero'),
  new Word('liú', '留', 'stay'),
  new Word('liú xià', '留下', 'stay; remain'),
  new Word('liú xué shēng', '留学生', 'student studying abroad; returned student'),
  new Word('liú', '流', 'flow; spread'),
  new Word('liúlì', '流利', 'fluent'),
  new Word('liúxíng', '流行', 'Popular'),
  new Word('lù biān', '路边', 'roadside; wayside'),
  new Word('lǚ kè', '旅客', 'passenger; traveler'),
  new Word('lǚxíng', '旅行', 'travel'),
  new Word('lǚyóu', '旅游', 'Tourism'),
  new Word('lǜ', '绿', 'green'),
  new Word('lǜ sè', '绿色', 'green'),
  new Word('mài', '卖', 'sell'),
  new Word('mǎn', '满', 'full'),
  new Word('mǎnyì', '满意', 'Satisfied'),
  new Word('māo', '猫', 'cat'),
  new Word('mǐ', '米（量）', 'meter'),
  new Word('miàn ¹', '面¹（名、量）', '(measure word); side; aspect'),
  new Word('miàn ²', '面²（名）', 'face; surface; outside; side; scale; flour'),
  new Word('miàn qián', '面前', 'in front of; before'),
  new Word('míng', '名', 'name'),
  new Word('míng chēng', '名称', 'name; designation'),
  new Word('míng dān', '名单', 'list'),
  new Word('míngxīng', '明星', 'Star'),
  new Word('mùdì', '目的', 'objective'),
  new Word('ná chū', '拿出', 'take out'),
  new Word('ná dào', '拿到', 'get'),
  new Word('nà', '那（连）', 'then; in that case'),
  new Word('nà huìr', '那会儿', 'at that time; then'),
  new Word('nà me', '那么', 'like that; in that way'),
  new Word('nà shí hou ｜ nà shí', '那时候｜那时', 'at that time'),
  new Word('nà yàng', '那样', 'that kind; like that; such'),
  new Word('nán fāng', '南方', 'south'),
  new Word('nánguò', '难过', 'Sorry'),
  new Word('nán kàn', '难看', 'ugly'),
  new Word('nánshòu', '难受', 'Uncomfortable'),
  new Word('nán tí', '难题', 'problem; difficult problem; puzzle'),
  new Word('nán tīng', '难听', 'unpleasant to hear'),
  new Word('néng gòu', '能够', 'be able to; can'),
  new Word('niánjí', '年级', 'grade'),
  new Word('niánqīng', '年轻', 'Young'),
  new Word('niǎo', '鸟', 'bird'),
  new Word('nòng', '弄', 'get, make'),
  new Word('nǔlì', '努力', 'Strive'),
  new Word('pá', '爬', 'climb; creep; scramble'),
  new Word('páshān', '爬山', 'Mountain climbing'),
  new Word('pà', '怕（动）', 'be afraid; fear; dread'),
  new Word('pái', '排（名、量）', 'row; line'),
  new Word('páiduì', '排队', 'queue; stand in a line'),
  new Word('pái qiú', '排球', 'volleyball'),
  new Word('pèng', '碰', 'touch, meet'),
  new Word('pèng dào', '碰到', 'meet; run into; bump into'),
  new Word('pèng jiàn', '碰见', 'meet; run into; bump into'),
  new Word('piān', '篇', 'piece'),
  new Word('piányi', '便宜', 'Cheap'),
  new Word('piàn', '片', 'slice'),
  new Word('piàoliang', '漂亮', 'Well done!； beautiful'),
  new Word('píng', '平', 'flat'),
  new Word('píng’ān', '平安', 'sound and safe'),
  new Word('píngcháng', '平常', 'Usual'),
  new Word('píngděng', '平等', 'equality'),
  new Word('píngshí', '平时', 'peacetime'),
  new Word('píng', '瓶', 'bottle'),
  new Word('píngzi', '瓶子', 'Bottle'),
  new Word('pǔ tōng', '普通', 'ordinary; general; average; common'),
  new Word('pǔtōnghuà', '普通话', 'Mandarin'),
  new Word('qítā', '其他', 'Other'),
  new Word('qízhōng', '其中', 'among'),
  new Word('qí', '骑', 'ride'),
  new Word('qí chē', '骑车', 'cycle'),
  new Word('qǐfēi', '起飞', 'take off'),
  new Word('qì', '气', 'air; gas; breath'),
  new Word('qì wēn', '气温', 'air temperature'),
  new Word('qiān', '千', 'thousand'),
  new Word('qiān kè', '千克', 'kilogram'),
  new Word('qián nián', '前年', 'the year before last'),
  new Word('qiáng', '墙', 'wall'),
  new Word('qīng nián', '青年', 'youth; young'),
  new Word('qīngshàonián', '青少年', 'Teenagers'),
  new Word('qīng', '轻', 'light'),
  new Word('qīngchu', '清楚', 'clear'),
  new Word('qíng', '晴', 'Sunny'),
  new Word('qíng tiān', '晴天', 'sunny day'),
  new Word('qǐng kè', '请客', 'stand treat; entertain'),
  new Word('qǐngqiú', '请求', 'request'),
  new Word('qiū tiān', '秋天', 'fall; autumn'),
  new Word('qiú', '求', 'request; beg; entreat; beseech'),
  new Word('qiú chǎng', '球场', 'court; field'),
  new Word('qiú duì', '球队', 'team'),
  new Word('qiú xié', '球鞋', 'sneakers; gym shoes'),
  new Word('qǔ', '取', 'take'),
  new Word('qǔ dé', '取得', 'acquire; gain; obtain'),
  new Word('quán', '全', 'whole; entire; complete'),
  new Word('quánbù', '全部', 'whole'),
  new Word('quán guó', '全国', 'nationwide; entire country'),
  new Word('quán jiā', '全家', 'whole family'),
  new Word('quán nián', '全年', 'annual; yearly'),
  new Word('quán shēn', '全身', 'whole body'),
  new Word('quán tǐ', '全体', 'all; entire; whole'),
  new Word('ránhòu', '然后', 'Then'),
  new Word('ràng', '让', 'Give Way'),
  new Word('rèqíng', '热情', 'Enthusiasm'),
  new Word('rénkǒu', '人口', 'population'),
  new Word('rén men', '人们', 'people'),
  new Word('rén shù', '人数', 'number of people'),
  new Word('rènwéi', '认为', 'think'),
  new Word('rì bào', '日报', 'daily, journal'),
  new Word('rìzi', '日子', 'life, days'),
  new Word('rúguǒ', '如果', 'If'),
  new Word('rùkǒu', '入口', 'Entrance'),
  new Word('shāngliang', '商量', 'discuss'),
  new Word('shāng rén', '商人', 'businessman'),
  new Word('shàng zhōu', '上周', 'last week'),
  new Word('shǎo shù', '少数', 'small number; few; minority'),
  new Word('shào nián', '少年', 'juvenile; young person'),
  new Word('shēn biān', '身边', 'at [by] one’s side'),
  new Word('shén me yàng', '什么样', 'what kind'),
  new Word('shēng', '生（动）', 'give birth; be born'),
  new Word('shēng cí', '生词', 'new word'),
  new Word('shēnghuó', '生活', 'Life'),
  new Word('shēngyīn', '声音', 'voice'),
  new Word('shěng', '省（名）', 'province'),
  new Word('shěng', '省（动）', 'economize; save; omit; leave out'),
  new Word('shífēn', '十分', 'very'),
  new Word('shíjì', '实际', 'Actual'),
  new Word('shíxí', '实习', 'Internship'),
  new Word('shíxiàn', '实现', 'Realization'),
  new Word('shízài', '实在', 'real; indeeed '),
  new Word('shízai', '实在', 'done carefully'),
  new Word('shíwù', '食物', 'food'),
  new Word('shǐyòng', '使用', 'Use'),
  new Word('shì', '市', 'city'),
  new Word('shì zhǎng', '市长', 'mayor'),
  new Word('shìqing', '事情', 'Thing'),
  new Word('shōu', '收', 'collect'),
  new Word('shōu dào', '收到', 'receive; obtain'),
  new Word('shōurù', '收入', 'income'),
  new Word('shǒubiǎo', '手表', 'Wrist Watch'),
  new Word('shòudào', '受到', 'Suffer'),
  new Word('shūfu', '舒服', 'comfortable'),
  new Word('shú', '熟', 'ripe; cooked; familiar; skilled'),
  new Word('shǔ', '数', 'to count'),
  new Word('shùzì', '数字', 'number'),
  new Word('shuǐpíng', '水平', 'level'),
  new Word('shùnlì', '顺利', 'smoothly'),
  new Word('shuōmíng', '说明', 'Explain'),
  new Word('sījī', '司机', 'Driver'),
  new Word('sòng dào', '送到', 'sent to (place)'),
  new Word('sòng gěi', '送给', 'give to (somebody or organization)'),
  new Word('suàn', '算', 'count; calculate'),
  new Word('suī rán', '虽然', 'although; though'),
  new Word('suíbiàn', '随便', 'casual'),
  new Word('suíshí', '随时', 'at any time'),
  new Word('suǒ yǐ', '所以', 'so'),
  new Word('suǒyǒu', '所有', 'All'),
  new Word('tā', '它', 'it'),
  new Word('tā men', '它们', 'they'),
  new Word('tàitai', '太太', 'Ma’am'),
  new Word('tàiyáng', '太阳', 'sun'),
  new Word('tàidu', '态度', 'attitude'),
  new Word('tǎolùn', '讨论', 'discuss'),
  new Word('tào', '套', 'set'),
  new Word('tèbié', '特别', 'Especially'),
  new Word('tèdiǎn', '特点', 'Characteristic'),
  new Word('téng', '疼', 'hurt'),
  new Word('tí', '提', 'carry'),
  new Word('tí chū', '提出', 'put forward; propose; raise'),
  new Word('tí dào', '提到', 'mention; refer to'),
  new Word('tígāo', '提高', 'increase, promote'),
  new Word('tí', '题', 'topic'),
  new Word('tǐyù', '体育', 'Sports'),
  new Word('tǐ yù chǎng', '体育场', 'stadium'),
  new Word('tǐ yù guǎn', '体育馆', 'stadium; gymnasium; gym'),
  new Word('tiān shàng', '天上', 'the sky; heaven'),
  new Word('tiáo', '条', 'strip'),
  new Word('tiáojiàn', '条件', 'condition'),
  new Word('tīng jiǎng', '听讲', 'attend a lecture; listen to a talk'),
  new Word('tīng shuō', '听说', 'be told; hear of'),
  new Word('tíng', '停', 'Stop'),
  new Word('tíng chē', '停车', 'park'),
  new Word('tíng chē chǎng', '停车场', 'parking lot'),
  new Word('tǐng', '挺（副）', 'very; quite; pretty; rather'),
  new Word('tǐng hǎo', '挺好', 'very good; not half bad'),
  new Word('tōng', '通', 'through; common; all; understand; expert'),
  new Word('tōngguò', '通过', 'adopt'),
  new Word('tōngzhī', '通知', 'notice'),
  new Word('tóngshí', '同时', 'meanwhile'),
  new Word('tóngshì', '同事', 'Colleague'),
  new Word('tóng yàng', '同样', 'same'),
  new Word('tóu', '头（名、量）', 'head; beginning or end; side; (measure word)'),
  new Word('tóu', '头（里头）', 'suffix (inside)'),
  new Word('tóufa', '头发', 'Hair'),
  new Word('tú piàn', '图片', 'picture; photograph'),
  new Word('tuī', '推', 'push'),
  new Word('tuǐ', '腿', 'leg'),
  new Word('wài dì', '外地', 'other places; nonlocal'),
  new Word('wài mài', '外卖', 'takeaway; take out'),
  new Word('wán', '完', 'finish'),
  new Word('wánchéng', '完成', 'complete'),
  new Word('wánquán', '完全', 'completely'),
  new Word('wǎn ān', '晚安', 'good night'),
  new Word('wǎn bào', '晚报', 'evening paper; evening news'),
  new Word('wǎn cān', '晚餐', 'dinner; supper'),
  new Word('wǎn huì', '晚会', 'evening party'),
  new Word('wǎn', '碗', 'bowl'),
  new Word('wàn', '万', 'ten thousand'),
  new Word('wǎng', '网', 'net; network'),
  new Word('wǎngqiú', '网球', 'Tennis'),
  new Word('wǎngzhàn', '网站', 'website'),
  new Word('wǎng', '往', 'to'),
  new Word('wèi', '为', 'by'),
  new Word('wèishénme', '为什么', 'Why'),
  new Word('wèi', '位', 'person (measure word)'),
  new Word('wèidào', '味道', 'taste'),
  new Word('wèi', '喂（叹）', 'hello; hey'),
  new Word('wēndù', '温度', 'temperature'),
  new Word('wén', '闻', 'smell'),
  new Word('wèn lù', '问路', 'ask for directions'),
  new Word('wèntí', '问题', 'problem'),
  new Word('wǔ cān', '午餐', 'lunch'),
  new Word('wǔ shuì', '午睡', 'nap'),
  new Word('xī běi', '西北', 'northwest'),
  new Word('xī cān', '西餐', 'western food'),
  new Word('xī fāng', '西方', 'west'),
  new Word('xī nán', '西南', 'southwest'),
  new Word('xī yī', '西医', 'western medicine'),
  new Word('xíguàn', '习惯', 'Habit'),
  new Word('xǐ yī jī', '洗衣机', 'washing machine'),
  new Word('xǐzǎo', '洗澡', 'Take a shower'),
  new Word('xià', '下（量）', '(measure word)'),
  new Word('xià xuě', '下雪', 'snow; snowing'),
  new Word('xià zhōu', '下周', 'next week'),
  new Word('xià tiān', '夏天', 'summer'),
  new Word('xiāngtóng', '相同', 'identical'),
  new Word('xiāngxìn', '相信', 'believe'),
  new Word('xiǎng', '响', 'loud '),
  new Word('xiǎng dào', '想到', 'think of; call to mind; have at heart'),
  new Word('xiǎng fǎ', '想法', 'idea; opinion;thought'),
  new Word('xiǎng qǐ', '想起', 'remember; recall; think of; call to mind'),
  new Word('xiàng', '向', 'towards'),
  new Word('xiàng jī', '相机', 'camera'),
  new Word('xiàng', '像（动）', 'be like; resemble; look like; such as'),
  new Word('xiǎo （ xiǎo wáng ）', '小（小王）', 'prefix (Xiao Wang)'),
  new Word('xiǎo shēng', '小声', 'in a low voice; in whispers'),
  new Word('xiǎo shí hou', '小时候', 'in one’s childhood; when one was young'),
  new Word('xiǎoshuō', '小说', 'Novel'),
  new Word('xiǎoxīn', '小心', 'Look out'),
  new Word('xiǎo zǔ', '小组', 'group'),
  new Word('xiào yuán', '校园', 'campus; schoolyard'),
  new Word('xiàozhǎng', '校长', 'Principal'),
  new Word('xiàohua', '笑话', 'joke'),
  new Word('xiào huàr', '笑话儿', 'joke'),
  new Word('xié', '鞋', 'shoes'),
  new Word('xīn lǐ', '心里', 'in the heart; at heart'),
  new Word('xīnqíng', '心情', 'mood'),
  new Word('xīn zhōng', '心中', 'in the heart; at heart; in mind'),
  new Word('xīnwén', '新闻', 'news'),
  new Word('xìn', '信（名）', 'letter; mail; faith'),
  new Word('xìnhào', '信号', 'signal'),
  new Word('xìnxī', '信息', 'information'),
  new Word('xìnxīn', '信心', 'confidence'),
  new Word('xìnyòngkǎ', '信用卡', 'Credit card'),
  new Word('xīng xing', '星星', 'star'),
  new Word('xíngdòng', '行动', 'Get some action'),
  new Word('xíngrén', '行人', 'pedestrian'),
  new Word('xíngwéi', '行为', 'behavior'),
  new Word('xìng', '姓', 'surname'),
  new Word('xìng míng', '姓名', 'full name'),
  new Word('xiū jià', '休假', 'have a holiday; take a vacation; be on furlough'),
  new Word('xǔduō', '许多', 'many'),
  new Word('xuǎn', '选', 'choose; select; pick'),
  new Word('xuéqī', '学期', 'Semester'),
  new Word('xuě', '雪', 'Snow'),
  new Word('yánsè', '颜色', 'colour'),
  new Word('yǎn', '眼', 'eye'),
  new Word('yǎnjing', '眼睛', 'Eye'),
  new Word('yǎng', '养', 'raise; keep; support; cultivate'),
  new Word('yàngzi', '样子', 'A look'),
  new Word('yāoqiú', '要求', 'Requirement'),
  new Word('yào', '药', 'drug'),
  new Word('yào diàn', '药店', 'pharmacy'),
  new Word('yào piàn', '药片', 'pill'),
  new Word('yào shuǐ', '药水', 'liquid medicine; potion'),
  new Word('yěxǔ', '也许', 'perhaps'),
  new Word('yè', '夜', 'night'),
  new Word('yè lǐ', '夜里', 'at night'),
  new Word('yí bù fèn', '一部分', 'a part; a portion'),
  new Word('yídìng', '一定', 'Certain'),
  new Word('yígòng', '一共', 'Altogether'),
  new Word('yí huìr', '一会儿（副）', 'awhile; in a moment; presently'),
  new Word('yí lù píng ān', '一路平安', 'safe journey; have a pleasant journey'),
  new Word('yí lù shùn fēng', '一路顺风', 'Bon voyage'),
  new Word('yǐjīng', '已经', 'Already'),
  new Word('yǐ hòu', '以后', 'after; later on; afterwards; later'),
  new Word('yǐqián', '以前', 'before'),
  new Word('yǐ shàng', '以上', 'above; over'),
  new Word('yǐ wài', '以外', 'beyond; outside; other than; except'),
  new Word('yǐwéi', '以为', 'Think'),
  new Word('yǐ xià', '以下', 'below; under'),
  new Word('yǐzi', '椅子', 'Chair'),
  new Word('yìbān', '一般', 'commonly'),
  new Word('yì diǎn diǎn', '一点点', 'a little bit'),
  new Word('yì shēng', '一生', 'lifetime; all one’s life'),
  new Word('yìzhí', '一直', 'always'),
  new Word('yì', '亿', 'Billion'),
  new Word('yìjiàn', '意见', 'Opinion'),
  new Word('yìsi', '意思', 'Meaning'),
  new Word('yīn wèi', '因为', 'because'),
  new Word('yīn', '阴', 'Yin'),
  new Word('yīn tiān', '阴天', 'cloudy day; overcast sky'),
  new Word('yīn jié', '音节', 'syllable'),
  new Word('yīnyuè', '音乐', 'Music'),
  new Word('yīn yuè huì', '音乐会', 'concert'),
  new Word('yínháng', '银行', 'Bank'),
  new Word('yín háng kǎ', '银行卡', 'bank card'),
  new Word('yīnggāi', '应该', 'Should'),
  new Word('yīng wén', '英文', 'English'),
  new Word('yīng yǔ', '英语', 'English'),
  new Word('yǐng piàn', '影片', 'film; movie'),
  new Word('yǐngxiǎng', '影响', 'Influence'),
  new Word('yǒngyuǎn', '永远', 'forever'),
  new Word('yóu', '油', 'oil; fat; grease'),
  new Word('yóu kè', '游客', 'tourist; visitor'),
  new Word('yǒuhǎo', '友好', 'friendly'),
  new Word('yǒu kòngr', '有空儿', 'be free; at leisure'),
  new Word('yǒu rén', '有人', 'someone; there’s someone'),
  new Word('yǒu （ yì ） diǎnr', '有（一）点儿', 'a little bit'),
  new Word('yǒu yì si', '有意思', 'interesting; significant'),
  new Word('yòu', '又', 'also'),
  new Word('yú', '鱼', 'fish'),
  new Word('yǔyán', '语言', 'language'),
  new Word('yuánlái', '原来', 'Original; formerly'),
  new Word('yuányīn', '原因', 'Reason'),
  new Word('yuàn', '院', 'yard; compound; courtyard; college'),
  new Word('yuàn zhǎng', '院长', 'dean'),
  new Word('yuàn zi', '院子', 'courtyard; yard'),
  new Word('yuànyì', '愿意', 'Be willing'),
  new Word('yuè fèn', '月份', 'month'),
  new Word('yuèliang', '月亮', 'Moon'),
  new Word('yuè', '越', 'The more'),
  new Word('yuè lái yuè', '越来越', 'more and more'),
  new Word('yún', '云', 'cloud'),
  new Word('yùndòng', '运动', 'motion'),
  new Word('zán', '咱', 'we; us'),
  new Word('zánmen', '咱们', 'We'),
  new Word('zāng', '脏', 'dirty'),
  new Word('zǎo cān', '早餐', 'breakfast'),
  new Word('zǎo chén', '早晨', 'morning'),
  new Word('zǎo jiù', '早就', 'long since'),
  new Word('zěn me bàn', '怎么办', 'how to; what to do'),
  new Word('zěnmeyàng', '怎么样', 'How about'),
  new Word('zěn yàng', '怎样', 'how'),
  new Word('zhàn', '占', 'occupy'),
  new Word('zhàn', '站（动）', 'stand; stop; halt'),
  new Word('zhàn zhù', '站住', 'stop; halt'),
  new Word('zhǎng', '长', 'grow'),
  new Word('zhǎng dà', '长大', 'grow up'),
  new Word('zhǎo chū', '找出', 'find out'),
  new Word('zhàogù', '照顾', 'look after'),
  new Word('zhàopiàn', '照片', 'Photo'),
  new Word('zhào xiàng', '照相', 'take a picture; take a photograph'),
  new Word('zhè me', '这么', 'so; such; this way; like this'),
  new Word('zhè shí hou ｜ zhè shí', '这时候｜这时', 'at this moment; at this time'),
  new Word('zhè yàng', '这样', 'so; such; like this; this way'),
  new Word('zhēnzhèng', '真正', 'real'),
  new Word('zhèngcháng', '正常', 'normal'),
  new Word('zhènghǎo', '正好', 'Just right'),
  new Word('zhèngquè', '正确', 'Correct'),
  new Word('zhèng shì', '正是', 'exactly'),
  new Word('zhíjiē', '直接', 'direct'),
  new Word('zhǐ', '只', 'only; just; simply; merely'),
  new Word('zhǐ néng', '只能', 'can only'),
  new Word('zhǐyào', '只要', 'as long as'),
  new Word('zhǐ', '纸', 'paper'),
  new Word('zhōng cān', '中餐', 'Chinese food'),
  new Word('zhōng jí', '中级', 'intermediate; middle-level'),
  new Word('zhōng nián', '中年', 'middle age; middle-aged'),
  new Word('zhōng xiǎo xué', '中小学', 'elementary and middle school'),
  new Word('zhōngxīn', '中心', 'core'),
  new Word('zhōng yī', '中医', 'Chinese Medicine'),
  new Word('zhòngdiǎn', '重点', 'A key'),
  new Word('zhòngshì', '重视', 'attach importance to'),
  new Word('zhōu', '周', 'week'),
  new Word('zhōumò', '周末', 'Weekend'),
  new Word('zhōunián', '周年', 'anniversary'),
  new Word('zhǔrén', '主人', 'master'),
  new Word('zhǔyào', '主要', 'main'),
  new Word('zhù fáng', '住房', 'housing; lodging'),
  new Word('zhù yuàn', '住院', 'be in hospital; be hospitalized'),
  new Word('zhuāng', '装', 'pretend'),
  new Word('zhǔnquè', '准确', 'accuracy'),
  new Word('zìjǐ', '自己', 'Own, self'),
  new Word('zìxíngchē', '自行车', 'Bicycle'),
  new Word('zìyóu', '自由', 'free'),
  new Word('zì diǎn', '字典', 'dictionary'),
  new Word('zǒu guò', '走过', 'walk through; pass by'),
  new Word('zǒu jìn', '走进', 'walk in'),
  new Word('zǒu kāi', '走开', 'go away'),
  new Word('zū', '租', 'rent'),
  new Word('zǔ', '组', 'group'),
  new Word('zǔchéng', '组成', 'Form'),
  new Word('zǔ zhǎng', '组长', 'group leader'),
  new Word('zuǐ', '嘴', 'mouth'),
  new Word('zuìjìn', '最近', 'Lately'),
  new Word('zuòjiā', '作家', 'writer'),
  new Word('zuòwén', '作文', 'composition'),
  new Word('zuòyè', '作业', 'task, homework'),
  new Word('zuòyòng', '作用', 'Effect'),
  new Word('zuò', '座', 'Seat'),
  new Word('zuòwèi', '座位', 'seat'),
  new Word('zuò dào', '做到', 'accomplish; achieve'),
  new Word('zuò fǎ', '做法', 'practice; behavior; way of doing a thing'),
  new Word('zuò fàn', '做饭', 'cook'),
]
