class Word {
	constructor (pinyin, character, translation){
    	this.pinyin = pinyin;
        this.character = character;
        this.translation = translation;
    }
}
wordArr = [
	new Word('āyí', '阿姨', 'aunt'),
	new Word('a', '啊', 'ah'),
	new Word('ǎi', '矮', 'short'),
	new Word('ài', '爱', 'love'),
	new Word('àihào', '爱好', 'hobby'),
	new Word('ānjìng', '安静', 'Be quiet'),
	new Word('bā', '八', 'Eight'),
	new Word('bǎ', '把', 'hold'),
	new Word('bàba', '爸爸', 'Dad'),
	new Word('ba', '吧', ''),
	new Word('bái', '白', 'white'),
	new Word('bǎi', '百', 'hundred'),
	new Word('bān', '班', 'class'),
	new Word('bān', '搬', 'turn; pull'),
	new Word('bàn', '半', 'half'),
	new Word('bànfǎ', '办法', 'Way'),
	new Word('bàngōngshì', '办公室', 'Office'),
	new Word('bāngmáng', '帮忙', 'Help'),
	new Word('bāngzhù', '帮助', 'Help'),
	new Word('bāo', '包', 'package'),
	new Word('bǎo', '饱', 'full'),
	new Word('bàozhǐ', '报纸', 'Newspaper'),
	new Word('bēizi', '杯子', 'glass'),
	new Word('běifāng', '北方', 'north'),
	new Word('běijīng', '北京', 'Beijing'),
	new Word('bèi', '被', 'cover'),
	new Word('běn', '本', 'book'),
	new Word('bízi', '鼻子', 'nose'),
	new Word('bǐ', '比', 'than'),
	new Word('bǐjiào', '比较', 'compare'),
	new Word('bǐsài', '比赛', 'Match'),
	new Word('bìxū', '必须', 'Must'),
	new Word('biànhuà', '变化', 'change'),
	new Word('biǎoshì', '表示', 'Express'),
	new Word('biǎoyǎn', '表演', 'perform'),
	new Word('bié', '别', 'other'),
	new Word('biéren', '别人', 'Others'),
	new Word('bīnguǎn', '宾馆', 'hotel'),
	new Word('bīngxiāng', '冰箱', 'Refrigerator'),
	new Word('búkèqi', '不客气', 'You are welcome'),
	new Word('bù', '不', 'No'),
	new Word('cái', '才', 'just'),
	new Word('cài', '菜', 'food'),
	new Word('càidān', '菜单', 'menu'),
	new Word('cānjiā', '参加', 'participate in'),
	new Word('cǎo', '草', 'grass'),
	new Word('céng', '层', 'layer'),
	new Word('chá', '茶', 'tea'),
	new Word('chà', '差', 'difference'),
	new Word('cháng', '长', 'long'),
	new Word('chànggē', '唱歌', 'Sing'),
	new Word('chāoshì', '超市', 'Supermarket'),
	new Word('chènshān', '衬衫', 'shirt'),
	new Word('chéngjì', '成绩', 'achievement'),
	new Word('chéngshì', '城市', 'City'),
	new Word('chī', '吃', 'eat'),
	new Word('chídào', '迟到', 'Late'),
	new Word('chū', '出', 'come out'),
	new Word('chūxiàn', '出现', 'Appear'),
	new Word('chūzūchē', '出租车', 'Taxi'),
	new Word('chúfáng', '厨房', 'Kitchen'),
	new Word('chúle', '除了', 'except'),
	new Word('chuān', '穿', 'Wear'),
	new Word('chuán', '船', 'ship'),
	new Word('chūn', '春', 'spring'),
	new Word('cíyǔ', '词语', 'terms'),
	new Word('cì', '次', 'second'),
	new Word('cōngming', '聪明', 'clever'),
	new Word('cóng', '从', 'from'),
	new Word('cuò', '错', 'Wrong'),
	new Word('dǎdiànhuà', '打电话', 'Phone'),
	new Word('dǎlánqiú', '打篮球', 'Play basketball'),
	new Word('dǎsǎo', '打扫', 'Clean'),
	new Word('dǎsuàn', '打算', 'Plan'),
	new Word('dà', '大', 'large'),
	new Word('dàjiā', '大家', 'everybody'),
	new Word('dài', '带', 'belt'),
	new Word('dānxīn', '担心', 'Worry'),
	new Word('dàngāo', '蛋糕', 'Cake'),
	new Word('dànshì', '但是', 'however'),
	new Word('dāngrán', '当然', 'Of course'),
	new Word('dào', '到', 'reach'),
	new Word('de', '地', 'adverbial'),
	new Word('de', '的', 'possession'),
	new Word('de', '得', 'appreciation'),
	new Word('dēng', '灯', 'lamp'),
	new Word('děng', '等', 'etc.'),
	new Word('dī', '低', 'low'),
	new Word('dìdi', '弟弟', 'Younger brother'),
	new Word('dìfang', '地方', 'local'),
	new Word('dìtiě', '地铁', 'metro'),
	new Word('dìtú', '地图', 'Map'),
	new Word('dìyī', '第一', 'first'),
	new Word('diǎn', '点', 'spot'),
	new Word('diànnǎo', '电脑', 'Computer'),
	new Word('diànshì', '电视', 'television'),
	new Word('diàntī', '电梯', 'Elevator.'),
	new Word('diànyǐng', '电影', 'Film'),
	new Word('diànzǐyóujiàn', '电子邮件', 'E-mail'),
	new Word('dōng', '东', 'east'),
	new Word('dōngxi', '东西', 'thing'),
	new Word('dōng', '冬', 'winter'),
	new Word('dǒng', '懂', 'understand'),
	new Word('dòngwù', '动物', 'Animal'),
	new Word('dōu', '都', 'all'),
	new Word('dú', '读', 'read'),
	new Word('duǎn', '短', 'short'),
	new Word('duàn', '段', 'paragraph'),
	new Word('duànliàn', '锻炼', 'Physical exercise'),
	new Word('duì', '对', 'Yes'),
	new Word('duìbuqǐ', '对不起', 'I’m sorry.'),
	new Word('duō', '多', 'many'),
	new Word('duōme', '多么', 'what'),
	new Word('duōshao', '多少', 'how much'),
	new Word('è', '饿', 'hungry'),
	new Word('érqiě', '而且', 'And'),
	new Word('érzi', '儿子', 'Son'),
	new Word('ěrduo', '耳朵', 'Ears'),
	new Word('èr', '二', 'Two'),
	new Word('fāshāo', '发烧', 'Have a fever'),
	new Word('fāxiàn', '发现', 'find'),
	new Word('fànguǎn', '饭馆', 'restaurant'),
	new Word('fāngbiàn', '方便', 'convenient'),
	new Word('fángjiān', '房间', 'Room'),
	new Word('fàng', '放', 'discharge'),
	new Word('fàngxīn', '放心', 'Don’t worry'),
	new Word('fēicháng', '非常', 'very'),
	new Word('fēijī', '飞机', 'aircraft'),
	new Word('fēn', '分', 'branch'),
	new Word('fēnzhōng', '分钟', 'Minute'),
	new Word('fúwùyuán', '服务员', 'Waiter'),
	new Word('fùjìn', '附近', 'nearby'),
	new Word('fùxí', '复习', 'Review'),
	new Word('gānjìng', '干净', 'clean'),
	new Word('gǎn', '敢', 'dare'),
	new Word('gǎnmào', '感冒', 'Cold'),
	new Word('gāngcái', '刚才', 'just'),
	new Word('gāo', '高', 'high'),
	new Word('gāoxìng', '高兴', 'happy'),
	new Word('gàosu', '告诉', 'tell'),
	new Word('gēge', '哥哥', 'brother'),
	new Word('gè', '个', 'individual'),
	new Word('gěi', '给', 'to'),
	new Word('gēn', '跟', 'with'),
	new Word('gēnjù', '根据', 'according to'),
	new Word('gèng', '更', 'more'),
	new Word('gōnggòngqìchē', '公共汽车', 'Bus'),
	new Word('gōngjīn', '公斤', 'Kg.'),
	new Word('gōngsī', '公司', 'company'),
	new Word('gōngyuán', '公园', 'Park'),
	new Word('gōngzuò', '工作', 'work'),
	new Word('gǒu', '狗', 'Dog'),
	new Word('gùshi', '故事', 'Story'),
	new Word('guāfēng', '刮风', 'Windy'),
	new Word('guān', '关', 'shut'),
	new Word('guānxì', '关系', 'relationship'),
	new Word('guānxīn', '关心', 'Care for'),
	new Word('guānyú', '关于', 'about'),
	new Word('guì', '贵', 'Expensive'),
	new Word('guójiā', '国家', 'Country'),
	new Word('guǒzhī', '果汁', 'fruit juice'),
	new Word('guòqù', '过去', 'Past times'),
	new Word('guo', '过', 'too'),
	new Word('hái', '还', 'still'),
	new Word('háishì', '还是', 'still'),
	new Word('háizi', '孩子', 'Children'),
	new Word('hàipà', '害怕', 'Fear'),
	new Word('hànyǔ', '汉语', 'Chinese'),
	new Word('hǎo', '好', 'good'),
	new Word('hǎochī', '好吃', 'Yummy'),
	new Word('hào', '号', 'Number'),
	new Word('hē', '喝', 'drink'),
	new Word('hé', '和', 'and'),
	new Word('hé', '河', 'river'),
	new Word('hēi', '黑', 'black'),
	new Word('hēibǎn', '黑板', 'blackboard'),
	new Word('hěn', '很', 'very'),
	new Word('hóng', '红', 'red'),
	new Word('hòumiàn', '后面', 'behind'),
	new Word('hùzhào', '护照', 'passport'),
	new Word('huā', '花 （动）', 'Flower (move)'),
	new Word('huāyuán', '花园', 'Garden'),
	new Word('huà', '画', 'painting'),
	new Word('huài', '坏', 'bad'),
	new Word('huānyíng', '欢迎', 'Welcome'),
	new Word('huán', '还', 'still'),
	new Word('huánjìng', '环境', 'Environmental Science'),
	new Word('huàn', '换', 'change'),
	new Word('huáng', '黄', 'yellow'),
	new Word('huí', '回', 'return'),
	new Word('huídá', '回答', 'Answer'),
	new Word('huì', '会', 'can；be able to'),
	new Word('huìyì', '会议', 'Meeting'),
	new Word('huǒchēzhàn', '火车站', 'Train station'),
	new Word('huòzhě', '或者', 'perhaps'),
	new Word('jīchǎng', '机场', 'Airport'),
	new Word('jīdàn', '鸡蛋', 'Egg'),
	new Word('jīhū', '几乎', 'almost'),
	new Word('jīhuì', '机会', 'Opportunity'),
	new Word('jí', '极', 'extremely'),
	new Word('jǐ', '几', 'several'),
	new Word('jìde', '记得', 'remember'),
	new Word('jìjié', '季节', 'Season'),
	new Word('jiā', '家', 'home'),
	new Word('jiǎnchá', '检查', 'inspect'),
	new Word('jiǎndān', '简单', 'simple'),
	new Word('jiàn', '件', 'piece'),
	new Word('jiànkāng', '健康', 'Healthy'),
	new Word('jiànmiàn', '见面', 'meet'),
	new Word('jiǎng', '讲', 'speak'),
	new Word('jiāo', '教', 'teach'),
	new Word('jiǎo', '角', 'horn'),
	new Word('jiǎo', '脚', 'foot'),
	new Word('jiào', '叫', 'call'),
	new Word('jiàoshì', '教室', 'Classroom'),
	new Word('jiē', '接', 'meet'),
	new Word('jiēdào', '街道', 'Street'),
	new Word('jiéhūn', '结婚', 'marry'),
	new Word('jiéshù', '结束', 'End'),
	new Word('jiémù', '节目', 'program'),
	new Word('jiérì', '节日', 'festival'),
	new Word('jiějie', '姐姐', 'sister'),
	new Word('jiějué', '解决', 'Solve'),
	new Word('jiè', '借', 'borrow'),
	new Word('jièshào', '介绍', 'introduce'),
	new Word('jīntiān', '今天', 'Today'),
	new Word('jìn', '进', 'enter'),
	new Word('jìn', '近', 'near'),
	new Word('jīngcháng', '经常', 'Often'),
	new Word('jīngguò', '经过', 'after'),
	new Word('jīnglǐ', '经理', 'manager'),
	new Word('jiǔ', '九', 'Nine'),
	new Word('jiǔ', '久', 'long'),
	new Word('jiù', '旧', 'used'),
	new Word('jiù', '就', ''),
	new Word('jǔxíng', '举行', 'hold'),
	new Word('jùzi', '句子', 'sentence'),
	new Word('juéde', '觉得', 'Think'),
	new Word('juédìng', '决定', 'Decision'),
	new Word('kāfēi', '咖啡', 'Coffee'),
	new Word('kāi', '开', 'open'),
	new Word('kāishǐ', '开始', 'start'),
	new Word('kàn', '看', 'see'),
	new Word('kànjiàn', '看见', 'seeing'),
	new Word('kǎoshì', '考试', 'Examination'),
	new Word('kě', '渴', 'thirsty'),
	new Word('kě’ài', '可爱', 'Lovely'),
	new Word('kěnéng', '可能', 'Probably'),
	new Word('kěyǐ', '可以', 'Sure'),
	new Word('kè', '刻', 'moment'),
	new Word('kè', '课', 'course'),
	new Word('kèrén', '客人', 'Guest'),
	new Word('kōngtiáo', '空调', 'Air conditioner'),
	new Word('kǒu', '口', 'mouth'),
	new Word('kū', '哭', 'cry'),
	new Word('kùzi', '裤子', 'trousers'),
	new Word('kuài', '块', 'block'),
	new Word('kuài', '快', 'fast'),
	new Word('kuàilè', '快乐', 'happy'),
	new Word('kuàizi', '筷子', 'chopsticks'),
	new Word('lái', '来', 'come'),
	new Word('lán', '蓝', 'blue'),
	new Word('lǎo', '老', 'old'),
	new Word('lǎoshī', '老师', 'Teacher'),
	new Word('le', '了', ''),
	new Word('lèi', '累', 'tired'),
	new Word('lěng', '冷', 'cold'),
	new Word('lí', '离', 'leave'),
	new Word('líkāi', '离开', 'leave'),
	new Word('lǐ', '里', 'in'),
	new Word('lǐwù', '礼物', 'gift'),
	new Word('lìshǐ', '历史', 'History'),
	new Word('liǎn', '脸', 'face'),
	new Word('liànxí', '练习', 'Practice'),
	new Word('liǎng', '两', 'Two'),
	new Word('liàng', '辆', 'Car'),
	new Word('liǎojiě', '了解', 'understand'),
	new Word('línjū', '邻居', 'neighbor'),
	new Word('líng', '零', 'Zero'),
	new Word('liù', '六', 'Six'),
	new Word('lóu', '楼', 'floor'),
	new Word('lù', '路', 'road'),
	new Word('lǚyóu', '旅游', 'Tourism'),
	new Word('lǜ', '绿', 'green'),
	new Word('māma', '妈妈', 'Mom'),
	new Word('mǎ', '马', 'Horse'),
	new Word('mǎshàng', '马上', 'Right off'),
	new Word('ma', '吗', ''),
	new Word('mǎi', '买', 'buy'),
	new Word('mài', '卖', 'sell'),
	new Word('mǎnyì', '满意', 'Satisfied'),
	new Word('màn', '慢', 'slow'),
	new Word('máng', '忙', 'busy'),
	new Word('māo', '猫', 'cat'),
	new Word('màozi', '帽子', 'Hat'),
	new Word('méi', '没', 'no'),
	new Word('méiguānxi', '没关系', 'No problem'),
	new Word('měi', '每', 'each'),
	new Word('mèimei', '妹妹', 'Younger sister'),
	new Word('mén', '门', 'door'),
	new Word('mǐ', '米', 'rice'),
	new Word('mǐfàn', '米饭', 'Steamed Rice'),
	new Word('miànbāo', '面包', 'Bread'),
	new Word('miàntiáo', '面条', 'noodle'),
	new Word('míngbai', '明白', 'clear'),
	new Word('míngtiān', '明天', 'Tomorrow'),
	new Word('míngzi', '名字', 'Name'),
	new Word('ná', '拿', 'take'),
	new Word('nǎ(nǎr)', '哪 （哪儿）', 'Which (where)'),
	new Word('nà(nàr)', '那 （那儿）', 'That (there)'),
	new Word('nǎinai', '奶奶', 'grandma'),
	new Word('nán', '南', 'south'),
	new Word('nánrén', '男人', 'Man'),
	new Word('nán', '难', 'disaster; blame'),
	new Word('nánguò', '难过', 'Sorry'),
	new Word('ne', '呢', ''),
	new Word('néng', '能', 'can'),
	new Word('nǐ', '你', 'you'),
	new Word('nián', '年', 'year'),
	new Word('niánjí', '年级', 'grade'),
	new Word('niánqīng', '年轻', 'Young'),
	new Word('niǎo', '鸟', 'bird'),
	new Word('nín', '您', 'you'),
	new Word('niúnǎi', '牛奶', 'milk'),
	new Word('nǔlì', '努力', 'Strive'),
	new Word('nǚ’ér', '女儿', 'daughter'),
	new Word('nǚrén', '女人', 'woman'),
	new Word('páshān', '爬山', 'Mountain climbing'),
	new Word('pánzi', '盘子', 'plate'),
	new Word('pángbiān', '旁边', 'Side'),
	new Word('pàng', '胖', 'fat'),
	new Word('pǎobù', '跑步', 'Run'),
	new Word('péngyou', '朋友', 'Friend'),
	new Word('píjiǔ', '啤酒', 'Beer'),
	new Word('piányi', '便宜', 'Cheap'),
	new Word('piào', '票', 'ticket'),
	new Word('piàoliang', '漂亮', 'Well done!'),
	new Word('píngguǒ', '苹果', 'Apple'),
	new Word('pútao', '葡萄', 'Grape'),
	new Word('pǔtōnghuà', '普通话', 'Mandarin'),
	new Word('qī', '七', 'Seven'),
	new Word('qīzi', '妻子', 'Wife'),
	new Word('qíshí', '其实', 'actually'),
	new Word('qítā', '其他', 'Other'),
	new Word('qí', '骑', 'ride'),
	new Word('qíguài', '奇怪', 'strange'),
	new Word('qǐchuáng', '起床', 'Get up'),
	new Word('qiān', '千', 'thousand'),
	new Word('qiānbǐ', '铅笔', 'pencil'),
	new Word('qián', '钱', 'money'),
	new Word('qiánmiàn', '前面', 'Front'),
	new Word('qīngchu', '清楚', 'clear'),
	new Word('qíng', '晴', 'Sunny'),
	new Word('qǐng', '请', 'please'),
	new Word('qiū', '秋', 'autumn'),
	new Word('qù', '去', 'go'),
	new Word('qùnián', '去年', 'Last year'),
	new Word('qúnzi', '裙子', 'skirt'),
	new Word('ránhòu', '然后', 'Then'),
	new Word('ràng', '让', 'Give Way'),
	new Word('rè', '热', 'heat'),
	new Word('rèqíng', '热情', 'Enthusiasm'),
	new Word('rén', '人', 'people'),
	new Word('rènshi', '认识', 'know'),
	new Word('rènwéi', '认为', 'think'),
	new Word('rènzhēn', '认真', 'earnest'),
	new Word('rì', '日', 'day'),
	new Word('róngyì', '容易', 'easily'),
	new Word('rúguǒ', '如果', 'If'),
	new Word('sān', '三', 'Three'),
	new Word('sǎn', '伞', 'umbrella'),
	new Word('shāngdiàn', '商店', 'Shop'),
	new Word('shàng', '上', 'upper'),
	new Word('shàngbān', '上班', 'go to work'),
	new Word('shàngwǎng', '上网', 'Surf the Internet'),
	new Word('shàngwǔ', '上午', 'morning'),
	new Word('shǎo', '少', 'less'),
	new Word('shéi', '谁', 'who'),
	new Word('shēntǐ', '身体', 'body'),
	new Word('shénme', '什么', 'What'),
	new Word('shēngbìng', '生病', 'Fall ill'),
	new Word('shēngqì', '生气', 'get angry'),
	new Word('shēngrì', '生日', 'Birthday'),
	new Word('shēngyīn', '声音', 'voice'),
	new Word('shí', '十', 'Ten'),
	new Word('shíhou', '时候', 'time'),
	new Word('shíjiān', '时间', 'time'),
	new Word('shǐ', '使', 'send'),
	new Word('shì', '是', 'yes'),
	new Word('shìjiè', '世界', 'world'),
	new Word('shìqing', '事情', 'Thing'),
	new Word('shǒubiǎo', '手表', 'Wrist Watch'),
	new Word('shǒujī', '手机', 'Mobile phone'),
	new Word('shòu', '瘦', 'thin'),
	new Word('shū', '书', 'book'),
	new Word('shūfu', '舒服', 'comfortable'),
	new Word('shūshu', '叔叔', 'uncle'),
	new Word('shù', '树', 'tree'),
	new Word('shùxué', '数学', 'Mathematics'),
	new Word('shuāyá', '刷牙', 'Brush one’s teeth'),
	new Word('shuāng', '双', 'double'),
	new Word('shuǐ', '水', 'water'),
	new Word('shuǐguǒ', '水果', 'Fruits'),
	new Word('shuǐpíng', '水平', 'level'),
	new Word('shuìjiào', '睡觉', 'sleep'),
	new Word('shuōhuà', '说话', 'speak'),
	new Word('sījī', '司机', 'Driver'),
	new Word('sì', '四', 'Four'),
	new Word('sòng', '送', 'give'),
	new Word('suīrán', '虽然', 'although'),
	new Word('suì', '岁', 'year'),
	new Word('suǒyǐ', '所以', 'therefore'),
	new Word('tā', '他', 'he'),
	new Word('tā', '她', 'she'),
	new Word('tā', '它', 'it'),
	new Word('tài', '太', 'too'),
	new Word('tàiyáng', '太阳', 'sunlight'),
	new Word('táng', '糖', 'sugar'),
	new Word('tèbié', '特别', 'Especially'),
	new Word('téng', '疼', 'They hurt'),
	new Word('tīzúqiú', '踢足球', 'Play football'),
	new Word('tí', '题', 'topic'),
	new Word('tígāo', '提高', 'increase'),
	new Word('tǐyù', '体育', 'Sports'),
	new Word('tiānqì', '天气', 'weather'),
	new Word('tián', '甜', 'sweet'),
	new Word('tiáo', '条', 'strip'),
	new Word('tiàowǔ', '跳舞', 'dance'),
	new Word('tīng', '听', 'hear'),
	new Word('tóngshì', '同事', 'Colleague'),
	new Word('tóngxué', '同学', 'Classmate'),
	new Word('tóngyì', '同意', 'Agree'),
	new Word('tóufa', '头发', 'Hair'),
	new Word('tūrán', '突然', 'suddenly'),
	new Word('túshūguǎn', '图书馆', 'Library'),
	new Word('tuǐ', '腿', 'leg'),
	new Word('wài', '外', 'abroad'),
	new Word('wán', '完', 'finish'),
	new Word('wánchéng', '完成', 'complete'),
	new Word('wán', '玩', 'play'),
	new Word('wǎn', '碗', 'bowl'),
	new Word('wǎnshang', '晚上', 'Night'),
	new Word('wàn', '万', 'ten thousand'),
	new Word('wàngjì', '忘记', 'forget'),
	new Word('wèi', '喂', 'feed'),
	new Word('wèi', '为', 'by'),
	new Word('wèile', '为了', 'in order to'),
	new Word('wèishénme', '为什么', 'Why'),
	new Word('wèi', '位', 'position'),
	new Word('wénhuà', '文化', 'Culture'),
	new Word('wèn', '问', 'ask'),
	new Word('wèntí', '问题', 'problem'),
	new Word('wǒ', '我', 'I'),
	new Word('wǒmen', '我们', 'We'),
	new Word('wǔ', '五', 'Five'),
	new Word('xī', '西', 'west'),
	new Word('xīguā', '西瓜', 'watermelon'),
	new Word('xīwàng', '希望', 'hope'),
	new Word('xíguàn', '习惯', 'Habit'),
	new Word('xǐ', '洗', 'wash'),
	new Word('xǐshǒujiān', '洗手间', 'Restroom'),
	new Word('xǐzǎo', '洗澡', 'Take a shower'),
	new Word('xǐhuan', '喜欢', 'like'),
	new Word('xià', '下', 'lower'),
	new Word('xiàwǔ', '下午', 'Afternoon'),
	new Word('xiàyǔ', '下雨', 'rain'),
	new Word('xià', '夏', 'summer'),
	new Word('xiān', '先', 'before'),
	new Word('xiānsheng', '先生', 'Sir'),
	new Word('xiànzài', '现在', 'Now'),
	new Word('xiāngjiāo', '香蕉', 'Banana'),
	new Word('xiāngtóng', '相同', 'identical'),
	new Word('xiāngxìn', '相信', 'believe'),
	new Word('xiǎng', '想', 'think'),
	new Word('xiàng', '向', 'towards'),
	new Word('xiàng', '像', 'image'),
	new Word('xiǎo', '小', 'Small'),
	new Word('xiǎojiě', '小姐', 'Miss'),
	new Word('xiǎoshí', '小时', 'hour'),
	new Word('xiǎoxīn', '小心', 'Look out'),
	new Word('xiào', '笑', 'laugh'),
	new Word('xiàozhǎng', '校长', 'Principal'),
	new Word('xiē', '些', 'some'),
	new Word('xié', '鞋', 'shoes'),
	new Word('xiě', '写', 'write'),
	new Word('xièxie', '谢谢', 'Thank you'),
	new Word('xīn', '新', 'new'),
	new Word('xīnwén', '新闻', 'Journalism'),
	new Word('xīnxiān', '新鲜', 'fresh'),
	new Word('xìn', '信', 'letter'),
	new Word('xīngqī', '星期', 'week'),
	new Word('xínglixiāng', '行李箱', 'Trunk'),
	new Word('xìng', '姓', 'surname'),
	new Word('xìngqù', '兴趣', 'Interest'),
	new Word('xióngmāo', '熊猫', 'Panda'),
	new Word('xiūxi', '休息', 'Rest'),
	new Word('xūyào', '需要', 'Need'),
	new Word('xuǎnzé', '选择', 'Choice'),
	new Word('xuésheng', '学生', 'Student'),
	new Word('xuéxí', '学习', 'Study'),
	new Word('xuéxiào', '学校', 'School'),
	new Word('xuě', '雪', 'Snow'),
	new Word('yánsè', '颜色', 'colour'),
	new Word('yǎnjìng', '眼镜', 'glasses'),
	new Word('yǎnjing', '眼睛', 'Eye'),
	new Word('yángròu', '羊肉', 'mutton'),
	new Word('yāoqiú', '要求', 'Requirement'),
	new Word('yào', '药', 'drug'),
	new Word('yào', '要', 'want'),
	new Word('yéye', '爷爷', 'grandpa'),
	new Word('yě', '也', 'also'),
	new Word('yī', '一', 'One'),
	new Word('yīfu', '衣服', 'clothes'),
	new Word('yīshēng', '医生', 'Doctor'),
	new Word('yīyuàn', '医院', 'Hospital'),
	new Word('yídìng', '一定', 'Certain'),
	new Word('yígòng', '一共', 'Altogether'),
	new Word('yíhuìr', '一会儿', 'A little while'),
	new Word('yíyàng', '一样', 'equally'),
	new Word('yǐhòu', '以后', 'In the future'),
	new Word('yǐqián', '以前', 'before'),
	new Word('yǐwéi', '以为', 'Think'),
	new Word('yǐjīng', '已经', 'Already'),
	new Word('yǐzi', '椅子', 'Chair'),
	new Word('yìbān', '一般', 'commonly'),
	new Word('yìbiān', '一边', 'One side'),
	new Word('yìqǐ', '一起', 'together'),
	new Word('yìzhí', '一直', 'always'),
	new Word('yìsi', '意思', 'Meaning'),
	new Word('yīn', '阴', 'Yin'),
	new Word('yīnwèi', '因为', 'because'),
	new Word('yīnyuè', '音乐', 'Music'),
	new Word('yínháng', '银行', 'Bank'),
	new Word('yīnggāi', '应该', 'Should'),
	new Word('yǐngxiǎng', '影响', 'Influence'),
	new Word('yòng', '用', 'use'),
	new Word('yóuxì', '游戏', 'Game'),
	new Word('yóuyǒng', '游泳', 'Swimming'),
	new Word('yǒu', '有', 'have'),
	new Word('yǒumíng', '有名', 'Famous'),
	new Word('yòu', '又', 'also'),
	new Word('yòubian', '右边', 'Right'),
	new Word('yú', '鱼', 'fish'),
	new Word('yùdào', '遇到', 'encounter'),
	new Word('yuán', '元', 'element'),
	new Word('yuǎn', '远', 'far'),
	new Word('yuànyì', '愿意', 'Be willing'),
	new Word('yuè', '月', 'month'),
	new Word('yuèliang', '月亮', 'Moon'),
	new Word('yuè', '越', 'The more'),
	new Word('yún', '云', 'cloud'),
	new Word('yùndòng', '运动', 'motion'),
	new Word('zài', '在', 'stay'),
	new Word('zài', '再', 'again'),
	new Word('zàijiàn', '再见', 'Bye'),
	new Word('zǎoshang', '早上', 'Morning'),
	new Word('zěnme', '怎么', 'How'),
	new Word('zěnmeyàng', '怎么样', 'How'),
	new Word('zhàn', '站', 'station'),
	new Word('zhāng', '张', 'Zhang'),
	new Word('zhǎng', '长', 'long'),
	new Word('zhàngfu', '丈夫', 'husband'),
	new Word('zháojí', '着急', 'Worry'),
	new Word('zhǎo', '找', 'look for'),
	new Word('zhàogù', '照顾', 'look after'),
	new Word('zhàopiàn', '照片', 'Photo'),
	new Word('zhàoxiàngjī', '照相机', 'Camera'),
	new Word('zhè(zhèr)', '这 （这儿）', 'Here (here)'),
	new Word('zhe', '着', 'means'),
	new Word('zhēn', '真', 'really'),
	new Word('zhèngzài', '正在', 'Is'),
	new Word('zhīdào', '知道', 'know'),
	new Word('zhǐ', '只', 'only'),
	new Word('zhōngguó', '中国', 'China'),
	new Word('zhōngjiān', '中间', 'Middle'),
	new Word('zhōngwǔ', '中午', 'Noon'),
	new Word('zhōngyú', '终于', 'finally'),
	new Word('zhǒng', '种', 'species'),
	new Word('zhòngyào', '重要', 'important'),
	new Word('zhōumò', '周末', 'Weekend'),
	new Word('zhǔyào', '主要', 'main'),
	new Word('zhù', '住', 'live'),
	new Word('zhù', '祝', 'wish'),
	new Word('zhùyì', '注意', 'Be careful'),
	new Word('zhǔnbèi', '准备', 'Get ready'),
	new Word('zhuōzi', '桌子', 'Table'),
	new Word('zì', '字', 'word'),
	new Word('zìdiǎn', '字典', 'Dictionaries'),
	new Word('zìjǐ', '自己', 'Own'),
	new Word('zìxíngchē', '自行车', 'Bicycle'),
	new Word('zǒngshì', '总是', 'always'),
	new Word('zǒu', '走', 'go'),
	new Word('zuì', '最', 'most'),
	new Word('zuìjìn', '最近', 'Lately'),
	new Word('zuótiān', '昨天', 'Yesterday'),
	new Word('zuǒbian', '左边', 'left'),
	new Word('zuò', '坐', 'sit'),
	new Word('zuò', '做', 'do'),
	new Word('zuòyè', '作业', 'homework'),
	new Word('zuòyòng', '作用', 'Effect')
]
